server:
  port: 9003
  servlet:
    context-path: /soul
spring:
  config:
    location: src/main/resources/application.yml
emo:
  startfilepath: "./soul/src/main/tmp/start.json"
  growthfilepath: "./soul/src/main/tmp/growth.json"